#!/usr/bin/env ruby
# Copyright (c) 2009-2010 Mario Carrion <mario@carrion.mx>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

require 'optparse'
require File.join(File.expand_path(File.dirname(__FILE__)), "repositories", "factory.rb")

options = {}
optparse = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} -p PATH"

  options[:path] = nil
  opts.on( '-p', '--path PATH', 'Path to detect repository.') do |path|
    options[:path] = path
  end

  opts.on( '-h', '--help', 'Display this screen.') do 
    puts opts 
    exit
  end
end
begin
  optparse.parse!
rescue OptionParser::InvalidOption, OptionParser::MissingArgument => e
  puts "Error: #{e}\nUse: #{File.basename(__FILE__)} -h for more information."
  exit 0
end

# No path provided, using working directory.
if options[:path].nil?
  options[:path] = Dir.pwd
end

repository = nil
Pulque::Factory::get_repositories(options[:path]).each do |repo|
  if repo.detect?
    repository = repo
    break
  end
end

if repository.nil?
  puts "abort: no repository detected."
else
  puts "#{repository.name}"
  puts "#{repository.friendly_name}"
  puts "#{repository.path}"
  puts "#{repository.repo_path}"
  puts "#{repository.branch}"
end
