.TH pcl 1  "April 16, 2010" "version 0.2" "USER COMMANDS"
.SH NAME
pcl \- prints ChangeLog information
.SH SYNOPSIS
.B pcl
.SH DESCRIPTION
This command shows you, depending on your files changed, the new
content to be added into your ChangeLog. This command basically
means "Print ChangeLog"
.SH AUTHOR
Mario Carrion <mario@carrion.mx>
.SH SEE ALSO
pfcl(1)
