.TH pexists 1  "January 26, 2010" "version 0.1" "USER COMMANDS"
.SH NAME
ppexists \- verifies existence of parallel development environment
.SH SYNOPSIS
.B pexists
[\-r root] [\-n name] 
.SH DESCRIPTION
Verifies existence of parallel environment. If one argument is provided then 
this is used as name.
.SH NOTE
By default the root used is: 
.B $HOME/.root-dev/
.PP
.SH AUTHOR
Mario Carrion <mario@carrion.mx>
.SH SEE ALSO
pswitch(1) pcreate(1)
