.TH plist 1  "January 26, 2010" "version 0.1" "USER COMMANDS"
.SH NAME
plist \- lists parallel environments available
.SH SYNOPSIS
.B plist
[\-r root]
.SH DESCRIPTION
List the current parallel environments created.
.SH NOTE
By default the root used is:
.B $HOME/.root-dev/
.SH AUTHOR
Mario Carrion <mario@carrion.mx>
.SH SEE ALSO
pswitch(1)
