.TH premove 1  "April 19, 2010" "version 0.2" "USER COMMANDS"
.SH NAME
premove \- removes a parallel development environment
.SH SYNOPSIS
.B premove
[\-r root] [\-n name]
.SH DESCRIPTION
Removes a previously created parallel environment. If one argument is
provided then this is used as name.
.SH NOTE
By default the root used is:
.B $HOME/.root-dev/
.PP
.SH AUTHOR
Mario Carrion <mario@carrion.mx>
.SH SEE ALSO
pcreate(1)
